name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx (for advanced builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to Docker Hub using your GitHub secret
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: akinfeayomide373
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 4: Build and push your Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: akinfeayomide373/my_page:latest

      # Step 5: Verify image build
      - name: Verify Docker image
        run: docker images
